datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: prometheus
     type: prometheus
     url: http://prometheus-server
     access: proxy
     isDefault: true
   - name: postgres
     type: postgres
     url: pg-postgresql:5432
     database: sfdata
     user: postgres
     secureJsonData:
      password: pg
     jsonData:
       sslmode: disable

dashboards:
  default:
    counts-dashboard:
      json: |
        {
          "annotations": {
            "list": [
              {
                "builtIn": 1,
                "datasource": "-- Grafana --",
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "type": "dashboard"
              }
            ]
          },
          "editable": true,
          "gnetId": null,
          "graphTooltip": 0,
          "id": 1,
          "links": [],
          "panels": [
            {
              "aliasColors": {},
              "bars": true,
              "dashLength": 10,
              "dashes": false,
              "datasource": "postgres",
              "fill": 1,
              "gridPos": {
                "h": 9,
                "w": 12,
                "x": 0,
                "y": 0
              },
              "id": 2,
              "legend": {
                "avg": false,
                "current": false,
                "max": false,
                "min": false,
                "show": false,
                "total": false,
                "values": false
              },
              "lines": false,
              "linewidth": 1,
              "nullPointMode": "connected",
              "options": {},
              "percentage": false,
              "pointradius": 2,
              "points": false,
              "renderer": "flot",
              "seriesOverrides": [],
              "spaceLength": 10,
              "stack": false,
              "steppedLine": false,
              "targets": [
                {
                  "format": "time_series",
                  "group": [],
                  "metricColumn": "none",
                  "rawQuery": true,
                  "rawSql": "SELECT\ncount as value,\ncountry as metric,\nnow() as time\nFROM counts\n\n",
                  "refId": "A",
                  "select": [
                    [
                      {
                        "params": [
                          "count"
                        ],
                        "type": "column"
                      }
                    ]
                  ],
                  "table": "counts",
                  "timeColumn": "count",
                  "timeColumnType": "int4",
                  "where": [
                    {
                      "name": "$__unixEpochFilter",
                      "params": [],
                      "type": "macro"
                    }
                  ]
                }
              ],
              "thresholds": [],
              "timeFrom": null,
              "timeRegions": [],
              "timeShift": null,
              "title": "Panel Title",
              "tooltip": {
                "shared": false,
                "sort": 0,
                "value_type": "individual"
              },
              "type": "graph",
              "xaxis": {
                "buckets": null,
                "mode": "series",
                "name": null,
                "show": true,
                "values": [
                  "current"
                ]
              },
              "yaxes": [
                {
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": null,
                  "show": true
                },
                {
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": null,
                  "show": true
                }
              ],
              "yaxis": {
                "align": false,
                "alignLevel": null
              }
            }
          ],
          "schemaVersion": 18,
          "style": "dark",
          "tags": [],
          "templating": {
            "list": []
          },
          "time": {
            "from": "now-6h",
            "to": "now"
          },
          "timepicker": {
            "refresh_intervals": [
              "5s",
              "10s",
              "30s",
              "1m",
              "5m",
              "15m",
              "30m",
              "1h",
              "2h",
              "1d"
            ],
            "time_options": [
              "5m",
              "15m",
              "1h",
              "6h",
              "12h",
              "24h",
              "2d",
              "7d",
              "30d"
            ]
          },
          "timezone": "",
          "title": "Counts",
          "uid": "JSr42WDWz",
          "version": 3
        }